lab50: true
files:
  - !exclude "*"
  - !include fahrenheit.c
  - !include truncate.c
  - !include pseudocode.txt
submit50:
  files:
  - !exclude "*"
  - !include "fahrenheit.c"
  - !include "pseudocode.txt"
